### PR TITLE
Rollbar official notifier support

### PR DESCRIPTION
**Pull request by rokob**
Hey I am the SDK engineer at Rollbar. We want to make Go one of our officially supported languages, and your library looks to me like the best place to start. I did a bare clone of your repo and pushed it up to https://github.com/rollbar/rollbar-go so that we don't end up with the official library as a fork of a fork, but we still want to maintain the git history.

We don't have any huge changes in mind at the moment, just some minor features to add, so this ideally won't be disruptive to your current use of the notifier. If there is some problem with this or another way you would prefer we proceed, please let me know.

I have looked through https://github.com/stvp/roll and https://github.com/stvp/rollbar as well, and think that your fork is the right starting point for how we see the notifier going forward.

I didn't see any other way to leave a comment on this repo besides opening a PR, so I created a simple documentation change that you can feel free to disregard for the time being.

### CODE REVIEW

**Comment by rokob** [comment]
@tysonmote this may interest you as well

**Comment by ryanbrainard** [comment]
@rokob Sorry, I just noticed this PR! Only 6 months late! Let me discuss it internally, but sounds good to me.

**Comment by ryanbrainard** [comment]
@rokob We discussed this internally, and it sounds good to us! Please let me know if you're still interested in making https://github.com/rollbar/rollbar-go the official repo. We've made a couple small updates on our repo, so it would be good if you could pick up those commits, and then we can merge this in and consider this repo deprecated.

**Comment by ryanbrainard** [comment]
@rokob Still interested in this?

**Comment by hazcod** [comment]
@ryanbrainard perhaps we should direct people to the rollbar-go repo in the README?

**Pull request merged**
